"""Added several field to model

Revision ID: 5b7158a8c728
Revises: ee1c6ab300e3
Create Date: 2021-03-31 15:46:22.930099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7158a8c728'
down_revision = 'ee1c6ab300e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('logistic_regression_spam', sa.Boolean(), nullable=True))
    op.add_column('email', sa.Column('random_forest_spam', sa.Boolean(), nullable=True))
    op.add_column('email', sa.Column('svm_spam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'svm_spam')
    op.drop_column('email', 'random_forest_spam')
    op.drop_column('email', 'logistic_regression_spam')
    # ### end Alembic commands ###
