"""empty message

Revision ID: df4142f2b783
Revises: 6cb11f949ff2
Create Date: 2021-04-21 15:37:32.939382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df4142f2b783'
down_revision = '6cb11f949ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'date_received')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('date_received', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
