"""empty message

Revision ID: eb1b6f657d8b
Revises: df4142f2b783
Create Date: 2021-04-26 15:02:17.715171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb1b6f657d8b'
down_revision = 'df4142f2b783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
