"""Added field to model

Revision ID: ee1c6ab300e3
Revises: d3de6ab81744
Create Date: 2021-03-04 20:42:44.564352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee1c6ab300e3'
down_revision = 'd3de6ab81744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email', 'date_received',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email', 'date_received',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
